# Generated by Django 4.1.4 on 2023-01-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
